### ISSUE TITLE
Include build instructions with source

### ISSUE THREAD

**Issue by miniatureape** [jonobr1/Physics#9]
Hello,

I think I have an issue, but I'd like to test with a built version of source code. I imagine you just run r.js on the src, but I was wondering if you could include build instructions with configuartion so my built source code looks exactly like yours does.

I poked around the repo and I don't see anything.

Thanks.

**Comment by jonobr1** [comment]
Thanks for checking out the library! Sorry for the lack of documentation on building. Everything you need to build is packaged with the repository. If you're in the repository you can just run in the command-line: `node ./utils/build`

I don't use r.js because of some irregularities with circular dependencies at the time of writing. It's totally possible that this is fixed now 😅 

If you look at the code in `./utils/` you'll notice that `build.js` just creates a set of parameters for `builder.js` to construct the concatenated and minified build versions of the project. Hope this helps!

**Comment by miniatureape** [comment]
Ah, fantastic. Worked like a charm.
